### ISSUE TITLE
Unzip will fail in Library directory

### ISSUE THREAD

**Issue by iori57** [ZipArchive/ZipArchive#160]
On iOS simulator, when I try to unzip in the Library directory, it fails. However in Document directory it succeeds. Anyone knows what's the problem?

I obtain the directory paths using the calls below:
```swift
var libraryDir = NSSearchPathForDirectoriesInDomains(.LibraryDirectory, .UserDomainMask, true)[0] as! String
var documentDir = NSSearchPathForDirectoriesInDomains(.DocumentDirectory, .UserDomainMask, true)[0] as! String
```

The full library directory path looks something like the below:
`"/Users/bruce/Library/Developer/CoreSimulator/Devices/6702D628-65BF-4611-B4FA-E3C838D5D167/data/Containers/Data/Application/8B5AB38F-7822-496A-88BE-E4BEB84DDC74/Library/ajax-indicator.zip"`

While the document directory path looks like the below:
`"/Users/bruce/Library/Developer/CoreSimulator/Devices/6702D628-65BF-4611-B4FA-E3C838D5D167/data/Containers/Data/Application/8B5AB38F-7822-496A-88BE-E4BEB84DDC74/Documents/ajax-indicator.zip"`

**Comment by istx25** [comment]
I am _pretty_ sure that that this failure is caused because of lack of privileges. 

Read this: This is the top-level directory for any files that are **not** user data files. You typically put files in one of several standard subdirectories. iOS apps commonly use the Application Support and Caches subdirectories. (taken from: https://developer.apple.com/library/prerelease/ios/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html)

But I could be wrong... :construction:
