### ISSUE TITLE
XCode 8

### ISSUE THREAD

**Issue by miniBloq** [ZipArchive/ZipArchive#276]
Hi, I tried today to add this library to my project using Carthage with XCode 8 Beta 6 (also using Swift 3) and got this linker error:

"error: The following binaries use incompatible versions of Swift:"

Could this be a Carthage bug, or could it be a ZivArchive one?

Thanks

**Comment by jhudsonWA** [comment]
I'm currently using it in Swift3, but don't use Carthage. Using
Cocoapods it seems to work fine with a Swift3 project

--
  Joshua Hudson
  joshua@hudsons.io



On Thu, Aug 18, 2016, at 02:03 PM, Julián da Silva Gillig wrote:
> Hi, I tried today to add this library to my project using Carthage
> with XCode 8 Beta 6 (also using Swift 3) and got this linker error:
> "error: The following binaries use incompatible versions of Swift:"
> Could this be a Carthage bug, or could it be a ZivArchive one?
> Thanks
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
>


Links:

  1. https://github.com/ZipArchive/ZipArchive/issues/276

**Comment by ianterrell** [comment]
@miniBloq I believe it might be the case that the prebuilt framework was built with an older version of Xcode. For all Swift dependencies before ABI stability, I recommend using `carthage bootstrap --no-use-binaries` so that you are guaranteed to build with the same Xcode version.

**Comment by miniBloq** [comment]
I tried, but got this error:

`$ carthage bootstrap --no-use-binaries
*** Checking out ZipArchive at "v1.5"
*** xcodebuild output can be found in /var/folders/_f/rpjhxdls3p966hqhkt0pd7h00000gp/T/carthage-xcodebuild.0anOS9.log
*** Building scheme "ZipArchive-Mac" in ZipArchive.xcodeproj
*** Building scheme "ZipArchive-iOS" in ZipArchive.xcodeproj
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/julian/projects/Harvard/Wyss/Square/v1.0/src/Carthage/Checkouts/ZipArchive/ZipArchive.xcodeproj -scheme ZipArchive-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
`

**Comment by jhudsonWA** [comment]
I will start building with xCode 8 once released. But that doesn't help now.

**Comment by miniBloq** [comment]
Yes, in fact, I started migrate now because the last stable (X7) and Betas (X8) can coexist. Once the new X8 stable is released, I think that the stable will be replaced (although I'm not 100% sure with this version.)

**Comment by jhudsonWA** [comment]
So my plan is that as soon as Xcode 8 and swift 3 is stable we will switch that that. Folks stuck on 2.3 or earlier versions of swift can use the currently released build.

**Comment by pk** [comment]
Hello,

So in order to use ZipArchive with Carthage and XCode 8 it is necessary to indicate which Swift version project uses, once that's done framework can be compiled, so that's one thing.

Because you can't link non Swift 3 Frameworks into your Swift 3 project you have decide what you want to support. But I can see a way to setup multiple targets for Swift, something like ZipArchive-Swift3 and ZipArchive-Swift23 which would allow appropriate settings of SWIFT_VERSION in XCode project. This setup would in Carthage build 3 frameworks (ZipArchive, ZipArchvie-Swift3 and ZipArchive-Swift23) and user would then link one which you need.

For Swift 3 code needs to be converted into Swift 3 which is trivially done with converter.

I've done Swift 3 changes in my fork: https://github.com/pk/ZipArchive
