### ISSUE TITLE
ioapi.c malloc: *** mach_vm_map(size=1950498816) failed (error code=3) *** error: can't allocate region

### ISSUE THREAD

**Issue by lansedebing** [ZipArchive/ZipArchive#327]
error happened in this code     strncpy(diskFilename, ioposix->filename, ioposix->filenameLength);

**Comment by wenninghui** [comment]
I also have this problem

**Comment by jhudsonWA** [comment]
Still an isssue? Test files or zip? Please try the new 2.0 branch if possible.

**Comment by leiguang** [comment]
I have the same error. And it print on the console: "malloc: *** mach_vm_map(size=1885487104) failed (error code=3)  *** error: can't allocate region".
My compression package has 180M, but I can create a new project can be successfully decompression, may be because the project has the duplicated library. How can i solve it? thanks!

**Comment by Coeur** [comment]
@leiguang please provide a sample project with the issue.
