### ISSUE TITLE
The event `zipArchiveDidUnzipArchiveFile` of protocol SSZipArchiveDelegate didn't work

### ISSUE THREAD

**Issue by VictorZhang2014** [ZipArchive/ZipArchive#387]
I'm using Xcode 9 and Swift 4, and conformed to the protocol `SSZipArchiveDelegate`, and implemented the function `func zipArchiveDidUnzipArchiveFile(_ zipFile: String, entryPath: String, destPath: String)`

Finally, I called this method `SSZipArchive.unzipFile(atPath: path, toDestination: tarpath, delegate:self)`, then it returned a `true`, its delegate events didn't invoke. 

I want to get help from you
Thank you in advance

**Comment by Coeur** [comment]
Well, it's unrelated to be Swift or ObjC. Apparently, this callback is missing... for years.

I'm reading the old commits to see what happened.

Then I'll take a decision on what to do.

**Comment by Coeur** [comment]
Callback was added by 713835cc28b896938dc5fe739a611f2e87553bec on 2 August 2012 and merged with https://github.com/ZipArchive/ZipArchive/pull/133 on 7 April 2015.

But on the same day, bddefcebfe636a7928afc36c9dbb209fa99a0430 lost the changes.

So it's equivalent of having never been here.

**Comment by Coeur** [comment]
zipArchiveDidUnzipFileAtIndex:totalFiles:archivePath:unzippedFilePath: has the same information (and more) as zipArchiveDidUnzipArchiveFile:entryPath:destPath: . So simply use:

        optional public func zipArchiveDidUnzipFile(at fileIndex: Int, totalFiles: Int, archivePath: String, unzippedFilePath: String)

I'll remove `func zipArchiveDidUnzipArchiveFile(_ zipFile: String, entryPath: String, destPath: String)`

**Comment by Coeur** [comment]
Note that instead of using a delegate, you can also use the completionHandler closure from:

**`open class func unzipFile(atPath path: String, toDestination destination: String, progressHandler: @escaping (String, unz_file_info, Int, Int) -> Swift.Void, completionHandler: @escaping (String, Bool, Error?) -> Swift.Void) -> Bool`**

---
Anyway, `zipArchiveDidUnzipArchiveFile` declaration is now removed with https://github.com/ZipArchive/ZipArchive/commit/b660cccd24671cfd4d984ede6452174c60c599af
