### ISSUE TITLE
Cannot compile for Swift 3.2 in Xcode 9

### ISSUE THREAD

**Issue by cannaz** [ZipArchive/ZipArchive#415]
I opened my project with Xcode 9 and I got this message:
`Module compiled with Swift 3.1 cannot be imported in Swift 3.2` , I did a clean, I deleted all the derived data and I updated carthage. Do you have any suggestions?

**Comment by Coeur** [comment]
Please use latest version of ZipArchive, [2.1.1](https://github.com/ZipArchive/ZipArchive/releases/tag/v2.1.1) or newer.

And be sure you're cleaning the derived data properly, as we're not using any swift code anymore. https://stackoverflow.com/a/6247073/1033581

**Comment by cannaz** [comment]
I did, that process does not solve my issue. I am using the `2.1.1`

**Comment by Coeur** [comment]
Then the issue is from a different lib, not from ZipArchive.
* our lib has no Swift code, so it can't generate that error
* our Swift sample works well with Swift 3, Swift 4, Xcode 8 and Xcode 9: https://github.com/ZipArchive/ZipArchive/tree/master/SwiftExample

Please try:
* to share a project that can reproduce the issue
* if you have issues at properly including a framework with Carthage, then you should move to CocoaPods instead

Good luck :)

**Comment by cannaz** [comment]
Solved it! The project that I am fixing does not use a workspace with Carthage and I had to replace the frameworks manually in the project, so I still had that error updating carthage and cleaning the derived data. Hope it is helpful for someone else.
