### ISSUE TITLE
Got too many symbol files warning message from iTunes Connect when using Carthage

### ISSUE THREAD

**Issue by zwang** [ZipArchive/ZipArchive#450]
I am using this library with my project which is using Swift 4.1 and Xcode 9.3

When we do an archive, and upload to iTunes connect, we got the following warning messages from iTunes Connect email:

> Dear Developer,
>
> We identified one or more issues with a recent delivery for your app, "Plato: Games, Chat & Friends". > Your delivery was successful, but you may wish to correct the following issues in your next delivery:
>
> Too many symbol files - These symbols have no corresponding slice in any binary [238100DF-7BA8-> 3876-9057-72EDB88D196F.symbols, C39F7EE4-66C4-38C3-AF89-F96DF51DD23C.symbols]
>
> After you’ve corrected the issues, you can use Xcode or Application Loader to upload a new binary to iTunes Connect.
>
> Best regards,
> 
> The App Store Team

Then in the archive -> dsym folder, I did `dwarfdump --uuid *`, found those UUIDs from ZipArchive

> UUID: 238100DF-7BA8-3876-9057-72EDB88D196F (armv7) ZipArchive.framework.dSYM/Contents/Resources/DWARF/ZipArchive
> UUID: C39F7EE4-66C4-38C3-AF89-F96DF51DD23C (arm64) ZipArchive.framework.dSYM/Contents/Resources/DWARF/ZipArchive

I have BitCode disabled for my project. Not sure if this is the reason.

**Comment by zwang** [comment]
Wondering if this is due to "Build Active Architecture Only" is "NO" for release build.

**Comment by jhudsonWA** [comment]
I don't have an app on the store, so I'm not sure. @Coeur?

**Comment by Coeur** [comment]
I have many Swift apps on the store using SSZipArchive, and I never got this kind of warning.
Be sure to use CocoaPods integration.

**Comment by MihaMajcen** [comment]
I've same issue as @zwang, ZipArchive is managed with Carthage, BitCode is disabled in project. 

Mail:

```
Too many symbol files - These symbols have no corresponding slice in any binary [C0ADD497-DA4D-3680-99D4-3E0C97863B10.symbols, E2CA1ADE-8051-37FB-8104-06B6BD64F506.symbols]
```

Dsyms:

```
dwarfdump -u ZipArchive.framework.dSYM

UUID: C0ADD497-DA4D-3680-99D4-3E0C97863B10 (armv7) 
ZipArchive.framework.dSYM/Contents/Resources/DWARF/ZipArchive

UUID: E2CA1ADE-8051-37FB-8104-06B6BD64F506 (arm64)
ZipArchive.framework.dSYM/Contents/Resources/DWARF/ZipArchive
```

There are 3 other dependencies included identically as ZipArchive, so I guess problem is not in my project config.

 @zwang did you solve this issue?

**Comment by Coeur** [comment]
@MihaMajcen I'm sorry, but if it works with CocoaPods and doesn't work with Carthage, then it's an integration issue.

We don't have any UUID symbol in our code source.

**Comment by Coeur** [comment]
@MihaMajcen Some colleague just had the same message today from Apple, without using SSZipArchive:
- Apple sends: "_Your delivery was successful, but you may wish to correct the following issues in your next delivery_", so it's not a blocking issue.
- people may encounter this issue with many frameworks when you incorrectly include some debugSymbols (dSYM).
- solutions are at https://stackoverflow.com/questions/25755240/too-many-symbol-files-after-successfully-submitting-my-apps

**Comment by MihaMajcen** [comment]
@Coeur thanks for all your responses.
I've already followed this stackoverflow's thread and found out that ZipArchive is causing this warnings in my project. 

Since I'm integrating library with Carthage I cannot change build settings, they are fetched from ZipArchive git repo. When I will found some time, I will fork this repo, change build settings and re upload new binary.  I will post my results here.

**Comment by zwang** [comment]
I did a fork and tried to disable bitcode in build settings, then the error is gone.

**Comment by Coeur** [comment]
@zwang OK, glad you got it resolved. Disabling bitcode was [Jerry Chen suggestion](https://stackoverflow.com/a/50582315/1033581) based on https://github.com/CocoaPods/CocoaPods/issues/7111 which confirms that it's an integration/configuration issue.

**Comment by MihaMajcen** [comment]
@zwang great to hear that. Can you post link to your fork? 
Thanks.

**Comment by Coeur** [comment]
@MihaMajcen zwang has currently two branches on his public fork:
- https://github.com/zwang/ZipArchive/tree/master
- https://github.com/zwang/ZipArchive/tree/plato

But to reiterate yet again: it's about how **you integrate** any third-party. There should be nothing to change on ZipArchive repository. If I got this wrong, please provide a pull request.

**Comment by MihaMajcen** [comment]
@Coeur yes, it is integration issue, I assume that problem is that my project has bitcode disabled.

Since I'm integrating ZipArchive via Carthage, I need to disable bitcode in ZipArchive source. If this is a correct fix, I suggest you to make separate branch with bitcode disabled. But first I will check if this is working in my project

**Comment by Coeur** [comment]
Now that my understanding of your issue has improved (you're using Carthage and you don't use bitcode), so I've temporary re-opened the issue.

But we can't satisfy simultaneously Bitcode users and non-Bitcode users.
So it's still an **integration** issue and it needs to be resolved by **you** (those doing `carthage update`), not by a fork.

You should look how to to configure Carthage to override Bitcode settings. Maybe you could apply this kind of steps:
https://github.com/Carthage/Carthage/issues/2440

**Comment by k3zi** [comment]
Another possible reason could be that ZipArchive supports down to 9.1 (and thus can run on armv7) but if your application is running on iOS 11 or higher, then you don't need to include armv7. However Xcode is not smart enough to know this and Carthage directly relies on `VALID_ARCHS` that Xcode provides. Additionally Xcode displays a warning if you try removing `armv7`. So instead of changing Xcode build settings I've gotten around this by removing `armv7` from the environmental variable when running Carthage:

```
VALID_ARCHS=${VALID_ARCHS//armv7 /} bash -c 'carthage copy-frameworks'
```

My application as well disables bitcode. I received this error from symbols across several frameworks. I'm not sure whether the correct solution should be bitcode or shipping architectures that are not supported by your app for frameworks. The latter seems more related to the issue but it's definitely not a problem of a library such as ZipArchive.

**Comment by jhudsonWA** [comment]
We have stopped including Carthage packages with our releases and leave it up to the developer to build their own framework from our source. As such these options are configurable. 

We don't plan to drop older OS's until at least a 3.x release so I'm closing this issue.
