### ISSUE TITLE
Possible infinite loop

### ISSUE THREAD

**Issue by jabcross** [ZipArchive/ZipArchive#467]
In line 469 of SSZipArchive.m, you have a possible infinite loop. If you pass a negative `nestedZipLevel`, I don't see anything keeping the recursive call from going on forever.

I didn't test it, though.

**Comment by Coeur** [comment]
In line 217 of the same file, if you change `nestedZipLevel:0` with `nestedZipLevel:-1`, all our current tests will still succeed: that is because this value is just setting the maximum depth to unzip when you have nested zip files (and our tests don't have nested zips...).

It's not an infinite loop: if you set it to a negative value, it will just unzip recursively archive files within archive files within archive files, etc.
