### ISSUE TITLE
[Security] dir traversal caused by symlink in zip

### ISSUE THREAD

**Issue by Proteas** [ZipArchive/ZipArchive#471]
PoC: https://github.com/Proteas/ZipArchive-Dir-Traversal-PoC

**Comment by Coeur** [comment]
Thanks, but again there is no explanation from you: your communication is a bit cryptic, that doesn't help to get things fixed.

I can only guess that you mean that we forgot to sanitise the destinationPath at https://github.com/ZipArchive/ZipArchive/blob/master/SSZipArchive/SSZipArchive.m#L569.

I'll look at it this weekend.

**Comment by Proteas** [comment]
if you can't read codes, maybe you can read this: https://www.anquanke.com/post/id/158502

**Comment by Coeur** [comment]
Thanks. I've read it at:
https://translate.google.com/translate?sl=zh-CN&tl=en&js=y&prev=_t&hl=fr&ie=UTF-8&u=https%3A%2F%2Fwww.anquanke.com%2Fpost%2Fid%2F158502&edit-text=&act=url

And it confirms that, while we dealt with most file name paths, we forgot symlink destination paths. I'll solve it soon.

**Comment by Coeur** [comment]
Actually not a bug: one can always create a symlink to anywhere on the filesystem: the permissions of the target are those that apply: https://unix.stackexchange.com/questions/358690/can-i-create-a-symbolic-link-to-a-file-i-cant-access

**Comment by jhudsonWA** [comment]
@proteas reached out on Twitter. Posting conversation here since this is the conversation thread.

**Comment by jhudsonWA** [comment]
![2006a510-c8ed-469a-a523-5be9fb3ebd14](https://user-images.githubusercontent.com/702446/44957134-3f416800-ae83-11e8-80aa-103fca1fffcd.png)

**Comment by jhudsonWA** [comment]
![19d8da9b-8ce2-4e80-a194-872b6616932e](https://user-images.githubusercontent.com/702446/44957138-554f2880-ae83-11e8-93e1-218aab2be48a.jpeg)

**Comment by Proteas** [comment]
Have you investigated the strategy of Apple（or other big companies with security dept. or famous unziping software） to deal with this problem?

**Comment by jhudsonWA** [comment]
Let me try to add some context to at least my thinking. With the main variant of ZipperDown the issue was an actual file could have a relative path and could be used for path traversal. We had a PR that was merged that successfully sanitized the file path, removing the relative links. All good.

Symlinks are a different type of a file. By definition they be pointed to anywhere in the system. **If we sanitize the file path then the symlink has been fundamentally changed and would no longer point to the same spot.**  Like @Coeur found, when it comes to if a symlink file should be allowed to be written at the path the systems permission system kicks in and will either allow it or not.

So why did we not accept your PR #454 ? Because your solution was to pass in a undocumented and poorly named parameter called "security". And the user of the library is supposed to know that if security is set to YES then symlinks are ignored. 

I'm not against adding a parameter and method signature to ignore symlinks in the file. But any proposed PR should be written in a way that lets the developer decide if they want to skip symlinks and be named, and documented in a way that they can see that is what the method signature does.

**Comment by jhudsonWA** [comment]
I can test apples archive program on Tuesday. But from quick google searches it appears it allows symlinked files to be zipped up. But i'd need to test on unzipping.
