### ISSUE TITLE
Which Version of Minizip is used and does it have same Security issues as in version 1.2 as documented.

### ISSUE THREAD

**Issue by modimoni** [ZipArchive/ZipArchive#475]
I am evaluating using the library for my Cordova plugin. But found that minizip is still in 1.2 version as per the documentation. 

 I found several security vulnerabilities in 1.2 version of minizip . I see that minizip was upgraded in 2.0.0 and many changes done as recent as Aug 2018  but did not specify the version of minizip used at present. I am looking for confirmation  that current version of minizip  in the latest version 2.1.4 of SSZipArchive don't have any Security vulnerabilities reported for minizip.

Thanks
Modi

**Comment by Coeur** [comment]
@modimoni Please link to those security issues.

We're using MiniZip 1.2 from https://github.com/Coeur/minizip/tree/master, a minor fork of https://github.com/nmoinvaz/minizip/tree/1.2, and I wasn't informed of any security issue in its current state.

**Comment by Coeur** [comment]
Note that there are plans to move to MiniZip2 as seen by #444, but the pull request is a bit outdated.

**Comment by modimoni** [comment]
I came across the issue https://www.cvedetails.com/vulnerability-list/vendor_id-17534/product_id-43048/year-2018/opdirt-1/Minizip-Project-Minizip.html

The same issue CVE-2014-9485 is listed in various portals.

I see the file mentioned in the issue is not added to SSZipArchive . Can you confirm.

**Comment by Coeur** [comment]
@modimoni : `miniunz.c` is just a demo file for the minizip library, so you're correct, we're not using it. The Directory traversal vulnerability was fixed in #456 (merged on 30 May 2018) which I further improved in #472 (commit on 7th Sept 2018) because it was breaking Unicode paths. This Unicode fix is currently only on Master branch: you can take the code from Master branch or wait for next bugfix release hopefully this weekend.

**Comment by modimoni** [comment]
Thanks a  lot for the proper information  information.
