### ISSUE TITLE
Error trying to decompress second file

### ISSUE THREAD

**Issue by FernandoHCN** [ZipArchive/ZipArchive#485]
First I download the first file, and I succeed when decompressing the file. But when I request the file to be downloaded again, it tries to decompress and crashes. I create an intermediate folder, I follow the example, and it works, however, when the second time it tries, then the error occurs.

I am getting the following error: **Error Domain = SSZipArchiveErrorDomain Code = -1 "failed to open zip file" UserInfo = {NSLocalizedDescription = failed to open zip file}**

**Comment by chenliangloveyou** [comment]
I have the same errors , no persion answer me .😊

**Comment by Coeur** [comment]
Using the example app (modified to always keep the same unzip path), unzipping twice at the same destination does not trigger any error, because we simply `overwrite` the previous files (unless you pass `overwrite: false` in the method call).

The only case where it could fail is if the file in the archive has readonly permissions, which means that once unzipped, it becomes forbidden to overwrite it. You can avoid that by passing `preserveAttributes: false` in the unzipping method call.

If that is not enough to solve your issue, please provide a sample project or files.

**Comment by zhangkiwi** [comment]
First use WinRAR to subcontract a file larger than 4GB, divide it into 20 sub-files, and then use SSZipArchive to decompress it. It will prompt: Error Domain=SSZipArchiveErrorDomain Code=-2 "failed to open first file in zip file"
