### ISSUE TITLE
Code=-3 "crc check failed for file"

### ISSUE THREAD

**Issue by LokoBeta** [ZipArchive/ZipArchive#533]
hello，there can not unzip a file, which zipped by adm-zip （https://github.com/cthackers/adm-zip）

use version 2.2.2

i see code failed in mz_zip.c line 1802

**Comment by tujinqiu** [comment]
same issue happened to me

**Comment by willson-chen** [comment]
@LokoBeta @tujinqiu hi, the link is unavaible. Could you please offer more details?

**Comment by willson-chen** [comment]
> @LokoBeta @tujinqiu hi, the link is unavaible. Could you please offer more details?

I found it. The browser jumpt to `https://github.com/cthackers/adm-zip）`, with a extra Chinese right parenthesis when I click the link in your description...

**Comment by willson-chen** [comment]
I compressed a file with adm-zip, then decompressed it using ziparchive, and found that the original crc (zip-> file_info.crc) and crc (zip-> entry_crc32) calculated by ziparchive were not equal.

Add the printed patch as follows:
```diff -up  mz_zip.c mz_zip_patch.c
--- mz_zip.c	2020-01-10 10:43:12.000000000 +0800
+++ mz_zip_patch.c	2020-01-10 10:42:44.000000000 +0800
@@ -2082,7 +2082,7 @@ int32_t mz_zip_entry_read_close(void *ha
             {
                 mz_zip_print("Zip - Entry - Crc failed (actual 0x%08"PRIx32" expected 0x%08"PRIx32")\n",
                     zip->entry_crc32, zip->file_info.crc);
-
+                printf("zip->entry_crc32:%x zip->file_info.crc:%x\n",zip->entry_crc32,zip->file_info.crc);
                 err = MZ_CRC_ERROR;
             }
         }
```

The print result is as follows:
```
zip->entry_crc32:69b86652 zip->file_info.crc:6652
```
So the problem lies in the crc calculation of adm-zip or ziparchive. I put the original file again at https://emn178.github.io/online-tools/crc32_checksum.html The crc calculated from this URL is also **69b86652**, which is the same as the crc calculated from the ziparchive printed above.


So there is reason to believe that the crc calculation method of adm-zip may not be so accurate.

zip file as follows:
[files.zip](https://github.com/ZipArchive/ZipArchive/files/4043822/files.zip)

Calculate crc file as follows(which is in zip file,this file's crc is **69b86652**):
[test.txt](https://github.com/ZipArchive/ZipArchive/files/4043819/test.txt)

**Comment by willson-chen** [comment]
Please check my findings. I think this issue belongs to add-zip.

**Comment by willson-chen** [comment]
@LokoBeta @tujinqiu The bug have been reported in [adm-zip/Issue #286](https://github.com/cthackers/adm-zip/issues/286). And here is the [resolvtion](https://github.com/cthackers/adm-zip/issues/289#issuecomment-520140501).

So I will close this issue. Any more question, please append comment.
