### ISSUE TITLE
Zip with password not work.

### ISSUE THREAD

**Issue by unicode612** [ZipArchive/ZipArchive#607]
### Steps to reproduce
1. WE download your demo and run
2. create a zip with a password
3. unzip file but not work

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

**Comment by pethanihiten** [comment]
Same issues with me.

**Comment by damhung-1510** [comment]
same issue..

**Comment by Coeur** [comment]
On top of unit tests for password support, there is an example app in the project which works perfectly fine with passwords:
https://github.com/ZipArchive/ZipArchive/tree/main/Example

So, kindly share a sample archive or a sample piece of code, otherwise your issue is not reproducible and not investigable.
