### ISSUE TITLE
Signing keys, access creds, API tokens: eventually compromised through Travis CI

### ISSUE THREAD

**Issue by Coeur** [ZipArchive/ZipArchive#625]
I just saw that:
https://twitter.com/peter_szilagyi/status/1437646118700175360

With 1.2k forks, we should investigate.

**Comment by jhudsonWA** [comment]
We haven't used Travis since May 30th, 2021 after they shut down the .org site & free unlimited build support for public builds. I did look at the account that was set up before then and no builds.

Also I'm not sure what secrets we would have in this library. We don't have to sign it on build. As Travis no longer has access to even the codebase here, I feel we are safe.

Your thoughts?

**Comment by Coeur** [comment]
OK. Thanks for the investigation.
