### ISSUE TITLE
Cannot extract AES-encrypted archives with a `£` character in the password using 7-Zip

### ISSUE THREAD

**Issue by tijme** [ZipArchive/ZipArchive#653]
A user of my app noticed that ZIP-archives with a `£` in the password cannot be decrypted. Please view the full details in the issue: https://github.com/raivo-otp/ios-application/issues/59.

### Steps to reproduce
1. Create an AES-encrypted ZIP-archive using this library with the password `££qqqqqq`
2. Export the file to a Windows machine
3. Try to decrypt it using 7-Zip

My code to create the ZIP-archive:

```
SSZipArchive.createZipFile(
    atPath: outputDirectory,
    withContentsOfDirectory: inputFilesPath,
    keepParentDirectory: false,
    compressionLevel: 0,
    password: password,
    aes: true
)
```

### Expected behavior
The ZIP-archive should be extracted. 

### Actual behavior
It states the password is incorrect. If I create a ZIP-archive with the password `qqqqqqqq` (without `££`) it does work, and 7-Zip is able to decrypt it.

### Version of ZipArchive
2.4.2

### Environmental information
Windows 11. iOS 15.

**Comment by Coeur** [comment]
While I do not have a Windows to investigate this, let's try the opposite scenario for now: can you attach a small sample zip file created on Windows with password `££qqqqqq`? I'll try to see if I can decompress it with ZipArchive on macOS.

**Comment by Coeur** [comment]
It seems that Raivo has terminated its issue tracker for https://github.com/raivo-otp/ios-application, so the "full details" aren't available anymore.
I can't help on this issue without a Windows machine, or without someone providing an archive made on Windows machine that does support `£` in its password.

**Comment by Coeur** [comment]
For reference, on iOS/macOS side, we have a unit test for Unicode password written by me in #377, which landed in ZipArchive 2.0.7:
https://github.com/ZipArchive/ZipArchive/blob/738a6b8bcb08bd107e38d3e7e5bd337632298e28/Example/ObjectiveCExampleTests/SSZipArchiveTests.m#L306

(the password for the test being "ꊐ⌒Ⅳ🤐")

**Comment by Coeur** [comment]
Except for compression level (which I set to `-1` instead of `0` like you), here are some archives made with the ZipArchive Example app.

Can you try them all on Windows 11, and share some feedback for the following programs:
1. Native unzipping support (double-click)
2. 7-Zip support (https://www.7-zip.org)
3. WinRar support (https://www.win-rar.com)
4. WinZip support (https://www.winzip.com)

## First example
This one is made from current main branch (aka ZipArchive 2.5.5-dev):
[738a6b8bcb08bd107e38d3e7e5bd337632298e28.zip](https://github.com/user-attachments/files/17017606/738a6b8bcb08bd107e38d3e7e5bd337632298e28.zip)
```
➜  ~ zipinfo -l 738a6b8bcb08bd107e38d3e7e5bd337632298e28.zip 
Zip file size: 234 bytes, number of entries: 1
-rw-r--r--  0.0 osx        4 BX       34 u099 24-Sep-16 20:06 test.txt
1 file, 4 bytes uncompressed, 22 bytes compressed:  -450.0%
```

It's extractable natively (with `££qqqqqq`) on macOS.

## Second example
This one is made from #716 branch:
[ed5ee8a1d577f5c2da64fd228d8d42196d2b19f4.zip](https://github.com/user-attachments/files/17017625/ed5ee8a1d577f5c2da64fd228d8d42196d2b19f4.zip)
```
➜  build zipinfo -l ed5ee8a1d577f5c2da64fd228d8d42196d2b19f4.zip 
Zip file size: 234 bytes, number of entries: 1
-rw-r--r--  3.0 unx        4 BX       34 u099 24-Sep-16 20:08 test.txt
1 file, 4 bytes uncompressed, 22 bytes compressed:  -450.0%
```

It's extractable natively (with `££qqqqqq`) on macOS.

## Third example
Our legacy unicode password sample, built from main branch (aka ZipArchive 2.5.5-dev):
[CreatedUnicodePasswordArchive.zip](https://github.com/user-attachments/files/17017692/CreatedUnicodePasswordArchive.zip)

It's extractable natively (with `ꊐ⌒Ⅳ🤐`) on macOS. I hope you can copy-paste.

**Comment by Coeur** [comment]
Some partial feedbacks that I got:
A. Native Windows 11 doesn't support passwords at all (it's 2024, and Microsoft didn't invent the word Security)
B. 7-zip support is broken for unicode passwords (please post a bug report to them: https://sourceforge.net/p/sevenzip/bugs/)
C. WinRar support is working fine for unicode passwords 🎉

**Comment by Coeur** [comment]
No feedback for 2 months, so I'll close it.

I hope you filled a bug report to 7-zip.
