### ISSUE TITLE
CVE-2022-36943 - lack of sanitization on paths which are symlinks

### ISSUE THREAD

**Issue by speedoholic** [ZipArchive/ZipArchive#662]
### Steps to reproduce
https://github.com/metaredteam/external-disclosures/security/advisories/GHSA-vgvw-6xcf-qqfc

### Expected behavior
Symlinks which are not relative to the destination path should be ignored unless the user explicitly requests it.

### Actual behavior
An attacker can embed a symlink in a ZIP archive pointing to a location of their choosing as the first file in the archive to first create the symlink. If a regular file in the ZIP has the same name as the symlink, the library will open and implicitly follow the symlink using an [fopen()](https://github.com/ZipArchive/ZipArchive/blob/b145c6f3619619fb48715c479643e2f2e0e42d2d/SSZipArchive/SSZipArchive.m#L496) call, and the contents of the file are written to the symlink target.

### Version of ZipArchive
<=2.5.3

**Comment by jhudsonWA** [comment]
Fixed in 2.5.4

**Comment by anton-patrushev** [comment]
Are there any plans to fix this vulnerability for releases before `2.5.0`?

As far as I know, there were introduced breaking changes with iOS 15+ as the minimal supported system OS version starting from the `2.5.0` release. It blocks me from fixing [the vulnerability](https://www.cve.org/CVERecord?id=CVE-2022-36943) due to minimal OS version requirements since I cannot upgrade the package version.

cc: @jhudsonWA

**Comment by jhudsonWA** [comment]
No. https://github.com/ZipArchive/ZipArchive/issues/692

**Comment by Coeur** [comment]
You may fork the project and attempt to lower the OS version requirements, but we're not supporting that ourselves.
