### ISSUE TITLE
SSZipArchive 2.5.5 fails to create zip which can be later converted to docx

### ISSUE THREAD

**Issue by sumitmorey** [ZipArchive/ZipArchive#693]
I am reintroducing SSZipArchive in my project as the path traversal related vulnerabilities are been fixed in 2.5.5. I am generating MS Word docx file. 2.2.2 and before version work smooth but with 2.5.5, I think, the directory contents  are not picked up and zipped as expected. 

v2.3.0 works as expected. The problem starts from v2.4.0. Alas I cannot use v2.3.0 as it is marked vulnerable by Veracode. Only 2.5.4 and 2.5.5 are valid to use.

### Steps to reproduce
1. Create zip using [SSZipArchive createZipFileAtPath:zipPath withContentsOfDirectory:sampleDataPath];
2. Zip gets generated 
3. Rename the zip to docx
4. Open the docx in MS Word
5. We see document recovery prompt
6. Export the file to Android device and it still fails to open

### Expected behavior
1. Similar to older versions, v2.5.5 should properly compress the contents of directory so can create perfect docx.
2. Works perfect on v2.2.2

### Actual behavior
Creates a zip. Rename it to docx. MS Word opens in recovery mode.

### Version of ZipArchive
SSZipArchive 2.5.5

### Environmental information
- Xcode 15.2
- iOS 16.6
- iPhone XR

[docx.zip](https://github.com/ZipArchive/ZipArchive/files/14278319/docx.zip)

**Comment by telcosolutions** [comment]
I'm having the same problem with creating an Excel file. After many hours of research, I've found that the zip must be:
compression method: deflated
compression sub-type: superfast
extended local header: no
file security status: not encrypted

See: ECMA, Office Open XML, Part 2 Open Packaging Conventions, 5th edition, December 2021

The problem is that I can't figure out what options to use to obtain that result. Hopefully, someone can help.

**Comment by telcosolutions** [comment]
I've tried a couple of older versions and so far find that a file created using version 2.3.0  works but not in 2.4.0. While there is still an extended local header Excel can read the file after changing zip to xlsx. Also, Numbers can also read the file without any error notification. I'm running the latest version of Xcode and IOS.

**Comment by Coeur** [comment]
You said the regression came with ZipArchive 2.4.0 which has mostly just a single behaviour change, the upgrade from minizip 2.9.2 to minizip 3.0.2.

Since then, there were various fixes, up to the latest minizip 4.0.7 in #724. So could you test the **main branch** (aka ZipArchive 2.6.1 or newer) and let me know if you still reproduce an issue with docx?

If you reproduce, can you clarify if it's still happening on **Windows** or **Mac**?

By the way, the document attached by @sumitmorey is not unzippable:
![Capture d’écran 2024-10-29 à 15 44 49](https://github.com/user-attachments/assets/64c2a59b-1ee9-40f3-88ae-fb50741a43ba)

So it's a suspicious archive in itself. The archives created with the sample ZipArchive app are extractable without issues (when you don't use a password).

**Comment by Coeur** [comment]
OK, I've reproduced the issue. The regression came with #613 and is still not fixed in current main branch. Tagging minizip.

**Comment by Coeur** [comment]
OK, it seems to me that the issue is because we're forcing zip64 format, which is incompatible with MS Word.
https://github.com/ZipArchive/ZipArchive/blob/4ce93ff4ff60b21bf0bbb7ccc2b1900d0f4435ac/SSZipArchive/minizip/mz_compat.c#L504-L505

I'll try to change it to AUTO
