### ISSUE TITLE
Project crashed when createZipFile

### ISSUE THREAD

**Issue by daiwj5** [ZipArchive/ZipArchive#694]
I‘m using SSZipArchive in my project, and my project is written by swift. There is my code below:
`
SSZipArchive.createZipFile(atPath: zipPath, withFilesAtPaths: [destinedPath])
`

and i got crash info:

`
Thread 1: EXC_BAD_ACCESS (code=1, address=0x14000006b9001be8)
`

which was triggered by createZipFile function, and finally stop at: 

![Xnip2024-02-26_10-37-30](https://github.com/ZipArchive/ZipArchive/assets/29176370/d689b991-f84e-4174-a7be-e67f3bb38828)

I have no idea about this, is there anyone met this situation before?

**Comment by 810152690** [comment]
我们遇到了，排查下来是有其他的三方库也定义了minizip里面函数，但是代码走到了其他库代码，从而引起crash

**Comment by ManOld** [comment]
有处理方法吗，也遇到楼主同样的问题

**Comment by Coeur** [comment]
ZipArchive has an example Xcode project example in Swift:
https://github.com/ZipArchive/ZipArchive/blob/be6ac340cbe394cc6a81eae6034a91a7702d9db3/Example/SwiftExample/ViewController.swift#L50

Since:
- that example project does not reproduce the crash
- your crash info just says there was a crash in [minizip](https://github.com/zlib-ng/minizip-ng)
- minizip was updated in #702.

I'll close this issue for now, and you'd need a reproducible example if you still encounter it with the latest commit of ZipArchive.
(potentially sharing example files that would cause the crash)
