### ISSUE TITLE
Is there any version update plan for iOS 12?

### ISSUE THREAD

**Issue by beibeiGeng** [ZipArchive/ZipArchive#695]
Hi, First of all, thank you for the open source software. Here are my doubts.
1) it's been two years since version 2.4.3 was released. That's a long time. Are there any plans for future updates? At present, the iOS system also supports iOS12.
2) If there is no update schedule: 2.4.3 version, in the case of compatible iOS12, can it support the new version released by Apple Inc? Is the version stable?
Please confirm, thank you very much.

**Comment by Coeur** [comment]
But let's be clear:
All iOS devices since the iPhone 6s released in 2015 can support iOS 15.5.
So the only devices you'd be losing by dropping iOS 12 support would be:
- iPhone 5S (2013)
- iPhone 6 and iPhone 6 Plus (2014)
- iPod Touch (6th generation) (2015)
- iPad Air (1st generation) (2013)
- iPad Mini 2 (2013)
- iPad Mini 3 (2014)

Are those devices worth compromising the security of your app?

**Comment by beibeiGeng** [comment]
According to the statistics, some users of my app have not upgraded to iOS15 and are still on iOS12. Therefore, I need to use version 2.4.3 to provide services for these users.

**Comment by Coeur** [comment]
That's a point of view.
Or, a malicious actor could keep using your app on an unsecured version to fake interest for such outdated version and keep you away from securing your app.
Anyway, you're a developer (or you have developers with you), so you should be easily able to figure out how to fork a dependency and adjust it to your needs.

**Comment by beibeiGeng** [comment]
Thank you for your reply. We will take your advice into consideration.
