### ISSUE TITLE
Whether to trigger the zlib vulnerability

### ISSUE THREAD

**Issue by beibeiGeng** [ZipArchive/ZipArchive#709]
Does the zipArchive software actively trigger the zilb vulnerability?

**Comment by Coeur** [comment]
So the topic is: https://nvd.nist.gov/vuln/detail/cve-2018-25032
Link says that old vulnerability (published 2 years ago) affects system zlib in:
- macOS From (including) 10.15	Up to (excluding) 10.15.7
- macOS From (including) 11.0	Up to (excluding) 11.6.6
- macOS From (including) 12.0.0	Up to (excluding) 12.4

The vulnerability only happens when uncompressing malicious archives on those systems.

So:
- If you're compressing and uncompressing only your own-made archives (not user-provided ones), you may be fine.

**Comment by Coeur** [comment]
Also for reference:
- #639
