### ISSUE TITLE
Deprecated Methods

### ISSUE THREAD

**Issue by prashant-ERA** [ZipArchive/ZipArchive#723]
### Steps to reproduce
1.
2.
3.

### Expected behavior
Tell us what should happen

### Actual behavior
Tell us what happens instead

### Version of ZipArchive
2.4.3
### Environmental information
I am using SSZipArchive in my iOS app and during code review it has been highlighted that the library uses deprecated methods like fopen, and strcpy. I am using version 2.4.3 of the repository. Please advice if you plan to update these deprecated methods to the latest methods in the updated version of the repository.

**Comment by Coeur** [comment]
`fopen` and `strcpy` aren't deprecated in Xcode Version 16.1 beta 3 (16B5029d).

And ZipArchive 2.4.3 isn't supported. We're at ZipArchive 2.6.0.

Since you mentioned "code review", I can only assume that you meant "App Store Connect review" and not some code review by a friend of yours. And if that's App Store Connect review, you should have a **Privacy Manifest** that was added in #688 (aka ZipArchive 2.5.5).

I'll close this issue due to the outdated ZipArchive version you're using and the absence of demonstration that there is any issue here with fopen and strcpy.
