### ISSUE TITLE
Cast pointer to int potentially losing precision in 64bit environment

### ISSUE THREAD

**Issue by limey** [ZipArchive/ZipArchive#90]
Appears to be casting of pointer to (int).
https://github.com/soffes/ssziparchive/blob/master/SSZipArchive/minizip/unzip.c#L218

According to Apple 64-bit transition guide, this would result in loss of precision when assigned back to ptr.  They suggest using uintptr_t.

https://developer.apple.com/library/ios/documentation/General/Conceptual/CocoaTouch64BitGuide/ConvertingYourAppto64-Bit/ConvertingYourAppto64-Bit.html#//apple_ref/doc/uid/TP40013501-CH3-SW3

**Comment by istx25** [comment]
Please create a PR with the related improvements. Thanks!

**Comment by istx25** [comment]
Anyone?

**Comment by Coeur** [comment]
This issue is referring to a version of minizip older than Feb 26, 2012.
This piece of code was updated by https://github.com/nmoinvaz/minizip/commit/aa4758baea16e9dc03583340e62b370ea1140df9 on Oct 10, 2016, and it was included in ZipArchive 2.0.0 (#350). I do not know if the issues from Apple 64-bit transition guide were fully addressed, but I believe there was an improvement.

Please create a new issue if you see any problem left, @limey.
